context("ICD-10-AM codes for the Charlson score are properly identified")

test_that("Charlson, ami, I21", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I21"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$ami, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, ami, I22", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I22"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$ami, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, ami, I252", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I252"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$ami, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, chf, I50", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I50"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$chf, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, pvd, I71", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I71"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pvd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, pvd, I790", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I790"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pvd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, pvd, I739", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I739"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pvd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, pvd, R02", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "R02"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pvd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, pvd, Z958", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "Z958"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pvd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, pvd, Z959", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "Z959"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pvd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, G450", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G450"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, G451", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G451"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, G452", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G452"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, G454", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G454"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, G458", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G458"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, G459", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G459"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, G46", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G46"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, I60-66 and I69", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I60"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I61"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I62"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I63"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I64"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I65"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I66"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I69"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, I670-679 except I673", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I670"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I671"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I672"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I674"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I675"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I676"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I677"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I678"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I679"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, cevd, I681-682 and I688", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I681"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I682"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "I688"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$cevd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, dementia, F00-02", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "F00"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$dementia, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "F01"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$dementia, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "F02"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$dementia, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, dementia, F051", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "F051"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$dementia, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, copd, J40-47", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J40"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J41"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J42"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J43"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J44"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J45"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J46"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J47"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, copd, J60-67", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J60"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J61"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J62"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J63"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J64"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J65"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J66"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "J67"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$copd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, rheumd, M050-053 and M058-059", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M050"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M051"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M052"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M053"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M058"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M059"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, rheumd, M060; M063; M069", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M060"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M063"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M069"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, rheumd, M32; M34; M332", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M32"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M34"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M332"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, rheumd, M353", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "M353"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rheumd, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, pud, K25-28", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K25"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pud, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K26"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pud, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K27"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pud, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K28"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$pud, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, mld, K702-703", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K702"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K703"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, mld, K717", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K717"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, mld, K73", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K73"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, mld, K740; K742-746", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K740"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K742"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K743"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K744"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K745"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K746"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$mld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E101", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E101"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E105", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E105"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E111", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E111"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E115", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E115"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E119", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E119"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E131", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E131"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E135", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E135"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E139", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E139"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E141", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E141"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E145", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E145"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diab, E149", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E149"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diab, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diabwc, E102-104", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E102"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E103"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E104"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diabwc, E112-114", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E112"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E113"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E114"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diabwc, E132-134", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E132"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E133"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E134"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, diabwc, E142-144", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E142"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E143"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "E144"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$diabwc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, hp, G041", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G041"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$hp, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, hp, G81", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G81"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$hp, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, hp, G820-822", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G820"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$hp, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G821"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$hp, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "G822"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$hp, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, rend, N01 and N03", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N01"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N03"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, rend, N052-057", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N052"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N053"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N054"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N055"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N056"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, rend, N18 and N19", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N18"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N19"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, rend, N25", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "N25"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$rend, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, canc, C0-3 and C5-6", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C0"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C1"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C2"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C3"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C5"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C6"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, canc, C40-49 except C42 and C44", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C40"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C41"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C43"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C45"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C46"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C47"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C48"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C49"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, canc, C70-76", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C70"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C71"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C72"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C73"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C74"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C75"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C76"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})
test_that("Charlson, canc, C81-85", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C81"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C82"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C83"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C84"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C85"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, canc, C883; C887; C889", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C883"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C887"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C889"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, canc, C900-901", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C900"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C901"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, canc, C940-943 and C947", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C940"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C941"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C942"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C943"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C947"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, canc, C9451", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C9451"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, canc, C91-93 and C95-96", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C91"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C92"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C93"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C95"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C96"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$canc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, msld, K721", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K721"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$msld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, msld, K729", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K729"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$msld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, msld, K766", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K766"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$msld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, msld, K767", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "K767"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$msld, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, metacanc, C77-80", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C77"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$metacanc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C78"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$metacanc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C79"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$metacanc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "C80"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$metacanc, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})

test_that("Charlson, aids, B20-24", {
  cs <- comorbidity(x = data.frame(id = "ID1", code = "B20"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$aids, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "B21"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$aids, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "B22"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$aids, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "B23"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$aids, expected = 1)
  expect_equal(object = cs$score, expected = 1)
  cs <- comorbidity(x = data.frame(id = "ID1", code = "B24"), id = "id", code = "code", score = "charlson", assign0 = "none", icd = "icd10am")
  expect_equal(object = cs$aids, expected = 1)
  expect_equal(object = cs$score, expected = 1)
})
