#' @keywords internal
.labelled <- function(x, map) {
  attr(x, "variable.labels") <-
    if (map == "elixhauser_ahrq_2022") {
      c(
        "ID",
        "Acquired immune deficiency syndrome",
        "Alcohol abuse",
        "Deficiency anemias",
        "Autoimmune conditions",
        "Chronic blood loss anemia",
        "Leukemia",
        "Lymphoma",
        "Metastatic cancer",
        "Solid tumor without metastasis, in situ",
        "Solid tumor without metastasis, malignant",
        "Cerebrovascular disease",
        "Coagulopathy",
        "Dementia",
        "Depression",
        "Diabetes with chronic complications",
        "Diabetes without chronic complications",
        "Drug abuse",
        "Heart failure",
        "Hypertension, complicated" ,
        "Hypertension, uncomplicated",
        "Liver disease, mild",
        "Liver disease, moderate to severe",
        "Chronic pulmonary disease",
        "Neurological disorders affecting movement",
        "Other neurological disorders",
        "Seizures and epilepsy",
        "Obesity",
        "Paralysis",
        "Peripheral vascular disease",
        "Psychoses",
        "Pulmonary circulation disease",
        "Renal failure, moderate",
        "Renal failure, severe" ,
        "Hypothyroidism",
        "Other thyroid disorders",
        "Peptic ulcer disease x bleeding",
        "Valvular disease",
        "Weight loss"
      )
    }
  else if (map == "elixhauser_ahrq_2020" |
           map == "elixhauser_ahrq_2021") {
    c(
      "ID",
      "Acquired immune deficiency syndrome",
      "Alcohol abuse",
      "Deficiency anemias",
      "Arthritis",
      "Chronic blood loss anemia",
      "Lymphoma",
      "Leukemia",
      "Metastatic cancer",
      "Solid tumor without metastasis, in situ",
      "Solid tumor without metastasis, malignant",
      "Cerebrovascular disease",
      "Chronic heart failure",
      "Coagulopathy",
      "Dementia",
      "Depression",
      "Diabetes with chronic complications",
      "Diabetes without chronic complications",
      "Drug abuse",
      "Hypertension, complicated" ,
      "Hypertension, uncomplicated",
      "Liver disease, mild",
      "Liver disease, moderate to severe",
      "Chronic pulmonary disease",
      "Neurological disorders affecting movement",
      "Other neurological disorders",
      "Seizures and epilepsy",
      "Obesity",
      "Paralysis",
      "Peripheral vascular disease",
      "Psychoses",
      "Pulmonary circulation disease",
      "Renal failure, moderate",
      "Renal failure, severe" ,
      "Hypothyroidism",
      "Other thyroid disorders",
      "Peptic ulcer disease x bleeding",
      "Valvular disease",
      "Weight loss"
    )
  }
  else if (grepl("^charlson_", map)) {
    c(
      "ID",
      "Myocardial infarction",
      "Congestive heart failure",
      "Peripheral vascular disease",
      "Cerebrovascular disease",
      "Dementia",
      "Chronic obstructive pulmonary disease",
      "Rheumatoid disease",
      "Peptic ulcer disease",
      "Mild liver disease",
      "Diabetes without chronic complications",
      "Diabetes with chronic complications",
      "Hemiplegia or paraplegia",
      "Renal disease",
      "Cancer (any malignancy)",
      "Moderate or severe liver disease",
      "Metastatic solid tumour",
      "AIDS/HIV"
    )
  } else {
    c(
      "ID",
      "Congestive heart failure",
      "Cardiac arrhythmias",
      "Valvular disease",
      "Pulmonary circulation disorders",
      "Peripheral vascular disorders",
      "Hypertension, uncomplicated",
      "Hypertension, complicated",
      "Paralysis",
      "Other neurological disorders",
      "Chronic pulmonary disease",
      "Diabetes, uncomplicated",
      "Diabetes, complicated",
      "Hypothyroidism",
      "Renal failure",
      "Liver disease",
      "Peptic ulcer disease excluding bleeding",
      "AIDS/HIV",
      "Lymphoma",
      "Metastatic cancer",
      "Solid tumour without metastasis",
      "Rheumatoid artritis/collaged vascular disease",
      "Coagulopathy",
      "Obesity",
      "Weight loss",
      "Fluid and electrolyte disorders",
      "Blood loss anaemia",
      "Deficiency anaemia",
      "Alcohol abuse",
      "Drug abuse",
      "Psychoses",
      "Depression"
    )
  }
  return(x)
}
