#' @keywords internal
.labelled <- function(x, map) {
  attr(x, "variable.labels") <- if (grepl("^charlson_", map)) {
    c("ID", "Myocardial infarction", "Congestive heart failure", "Peripheral vascular disease", "Cerebrovascular disease", "Dementia", "Chronic pulmonary disease", "Rheumatoid disease", "Peptic ulcer disease", "Mild liver disease", "Diabetes without chronic complications", "Diabetes with chronic complications", "Hemiplegia or paraplegia", "Renal disease", "Cancer (any malignancy)", "Moderate or severe liver disease", "Metastatic solid tumour", "AIDS/HIV")
  } else if (grepl("^m3_", map)) {
    labs = c( "ID", "AIDS/HIV", "Alcohol abuse", "Anemia deficiency", "Anxiety and Behavioural disorders", "Aortic and other aneurysms", "Bone disorders", "Bowel disease inflammatory", "Breast cancer", "Cardiac arrhythmia", "Cardiac valve", "Cerebrovascular disease", "Chronic pulmonary", "Chronic renal", "Coagulopathy and other blood disorders", "Colorectal cancer", "Congestive heart failure", "Connective tissue disease", "Dementia", "Diabetes (complicated)", "Diabetes (uncomplicated)", "Drug abuse", "Endocrine disorder", "Epilepsy", "Eye problem long term", "Gynaecological cancers", "Hepatitis, chronic viral", "Hypertension (uncomplicated)", "Immune system disorder", "Inner ear disorder", "Joint or spinal disorder", "Liver disease (moderate or severe)", "Lung cancer", "Lymphomas and leukaemias", "Major psychiatric disorder", "Malignant melanoma", "Malnutrition and other nutritional disorders", "Mental and behavioural disorders due to brain damage", "Mental retardation", "Metabolic disorder", "Metastatic cancer", "Muscular peripheral nerve disorders", "Myocardial infarction", "Obesity", "Osteoporosis (uncomplicated)", "Other cancers", "Other neurologic disorders (excluding epilepsy)", "Paralysis", "Peptic ulcer disease", "Peripheral vascular disease", "Prostate cancer", "Pulmonary circulation disorders", "Sleep disorder", "Upper gastrointestinal cancer", "Urinary tract problem (chronic)", "Venous insufficiency", "Angina", "Cardiac disease (other)", "Infection chronic NOS", "Intestinal disorder", "Pancreatitis", "Tuberculosis", "Flag for diabetes complications", "Flag for osteoporosis exclusions", "Flag for hypertension exclusions" )
  } else {
    c("ID", "Congestive heart failure", "Cardiac arrhythmias", "Valvular disease", "Pulmonary circulation disorders", "Peripheral vascular disorders", "Hypertension, uncomplicated", "Hypertension, complicated", "Paralysis", "Other neurological disorders", "Chronic pulmonary disease", "Diabetes, uncomplicated", "Diabetes, complicated", "Hypothyroidism", "Renal failure", "Liver disease", "Peptic ulcer disease excluding bleeding", "AIDS/HIV", "Lymphoma", "Metastatic cancer", "Solid tumour without metastasis", "Rheumatoid artritis/collaged vascular disease", "Coagulopathy", "Obesity", "Weight loss", "Fluid and electrolyte disorders", "Blood loss anaemia", "Deficiency anaemia", "Alcohol abuse", "Drug abuse", "Psychoses", "Depression")
  }
  return(x)
}