#' @keywords internal
.labelled <- function(x, map) {
  attr(x, "variable.labels") <- if (grepl("^charlson_", map)) {
    c("ID", "Myocardial infarction", "Congestive heart failure", "Peripheral vascular disease", "Cerebrovascular disease", "Dementia", "Chronic pulmonary disease", "Rheumatoid disease", "Peptic ulcer disease", "Mild liver disease", "Diabetes without chronic complications", "Diabetes with chronic complications", "Hemiplegia or paraplegia", "Renal disease", "Cancer (any malignancy)", "Moderate or severe liver disease", "Metastatic solid tumour", "AIDS/HIV")
  } else if (grepl("^m3_", map)) {
    c("ID", "Myocardial infarction", "Congestive heart failure", "Peripheral vascular disease", "Aortic and other aneurysms", "Venous insufficiency", "Cerebrovascular disease", "Dementia", "Mental and behavioural disorders due to brain damage", "Chronic obstructive pulmonary disease", "Connective tissue", "Peptic ulcer disease", "Diabetes, uncomplicated", "Diabetes, complicated", "Paralysis", "Renal disease", "Colorectal cancer", "Breast cancer", "Prostate cancer", "Lung cancer", "Lymphomas and leukaemias", "Upper gastrointestinal cancers", "Malignant melanoma", "Gynaecological cancers", "Other cancers", "Metastatic cancer", "Liver disease, moderate or severe", "AIDS/HIV", "Angina", "Hypertension, uncomplicated", "Cardiac arrhythmias", "Pulmonary circulation disorders", "Valvular disease", "Bowel disease inflammatory", "Other neurological disorders exc epilepsy", "Epilepsy", "Muscular peripheral nerve disorder", "Major psychiatric disorder", "Anxiety and Behavioural disorders", "Coagulopathy and other blood disorder", "Deficiency anaemia", "Obesity", "Alcohol abuse", "Drug abuse", "Pancreatitis", "Endocrine disorder", "Urinary tract problem chronic", "Tuberculosis", "Bone disorders", "Osteoporosis, uncomplicated", "Immune system disorder", "Metabolic disorder", "Mental retardation", "Chronic viral hepatitis", "Sleep disorder", "Inner ear disorder", "Chronic infection NOS", "Malnutrition nutritional", "Chronic eye problem", "Cardiac disease NOS", "Intestinal disorder", "Joint spinal disorder", "Flag for diabetes complications", "Flag for osteoporosis exclusions", "Flag for hypertension exclusions" )  
  }else {
    c("ID", "Congestive heart failure", "Cardiac arrhythmias", "Valvular disease", "Pulmonary circulation disorders", "Peripheral vascular disorders", "Hypertension, uncomplicated", "Hypertension, complicated", "Paralysis", "Other neurological disorders", "Chronic pulmonary disease", "Diabetes, uncomplicated", "Diabetes, complicated", "Hypothyroidism", "Renal failure", "Liver disease", "Peptic ulcer disease excluding bleeding", "AIDS/HIV", "Lymphoma", "Metastatic cancer", "Solid tumour without metastasis", "Rheumatoid artritis/collaged vascular disease", "Coagulopathy", "Obesity", "Weight loss", "Fluid and electrolyte disorders", "Blood loss anaemia", "Deficiency anaemia", "Alcohol abuse", "Drug abuse", "Psychoses", "Depression")
  }
  return(x)
}